### ISSUE TITLE
IBI calculation - potential data QC checks

### ISSUE THREAD

**Issue by leppott** [leppott/MBSStools#26]
**Is your feature request related to a problem? Please describe.**
Potential checks:
 
1.	Strata spellings.  Make sure all are of the correct convention (i.e., spelling).
2.	Exclude column.  TRUE/FALSE vs. other formats.
3.	Add a master taxa list check.  User provides and the master taxa list and reports back non-matches.
a.	Can do for fish and bugs.  Just need the lists.  If posted online much easier to update/distribute to the users but can put in a current version.
4.	Ensure samples with 0 organisms get an IBI of 1.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leppott** [comment]
Potentially could create a report of the number of taxa that do / do not have autecological information.  Concentrate on what is needed for IBI calculations.

- Phylo information
- habits
- FFG
- tolval (urban)
- fish groups

**Comment by leppott** [comment]
Could run a routine on Excluded taxa as defined by user vs. automated.

BioMonTools::markExcluded.

Could import routine so don't rely on another package.

https://github.com/leppott/BioMonTools/blob/master/man/markExcluded.Rd

https://github.com/leppott/BioMonTools/blob/master/doc/ExcludedTaxaDecisionCrit.pdf

**Comment by leppott** [comment]
Count vs. Non-Count taxa per MBSS protocols.

For example, MBSS does not include Acari (water mites) in its samples.

**Comment by leppott** [comment]
Min/Max individuals.

Min = 60
Max = __

**Comment by leppott** [comment]
Should check contents of FFG and Habit columns for accepted values.

**Comment by leppott** [comment]
Added QC check for 0 organisms.  Metric Scores and IBI are now "1".

Modified Code in metric.values().
![image](https://user-images.githubusercontent.com/24276278/82443563-b6f86180-9a6f-11ea-9b68-dbd2aedac549.png)

Warning message to user.
![image](https://user-images.githubusercontent.com/24276278/82443496-9af4c000-9a6f-11ea-9d7b-75a20db0f8c6.png)

**Comment by ashtonmj** [comment]
Erik,
I don’t think the 0 individuals = IBI of 1 holds true for bugs as it is for
fish. Again, I don’t know why there are so many basic inconsistencies
between them, but there are nevertheless. There are no 0 organisms benthic
samples in the database; either we don’t calculate it or maybe a sample was
re-taken?

Sent from my iPhone

On May 20, 2020, at 7:58 AM, Erik Leppo <notifications@github.com> wrote:

﻿

Added QC check for 0 organisms. Metric Scores and IBI are now "1".

Modified Code in metric.values().
[image: image]
<https://user-images.githubusercontent.com/24276278/82443563-b6f86180-9a6f-11ea-9b68-dbd2aedac549.png>

Warning message to user.
[image: image]
<https://user-images.githubusercontent.com/24276278/82443496-9af4c000-9a6f-11ea-9d7b-75a20db0f8c6.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/leppott/MBSStools/issues/26#issuecomment-631428855>, or
unsubscribe

**Comment by leppott** [comment]
Commented out the BUGS section.

![image](https://user-images.githubusercontent.com/24276278/82445179-5f0f2a00-9a72-11ea-8557-e1d6aa81ca2d.png)

For bugs have a post calculation set of code in the example to test for "large" and "small" samples.

![image](https://user-images.githubusercontent.com/24276278/82445281-8534ca00-9a72-11ea-9f98-21306c3972ea.png)

**Comment by leppott** [comment]
Master taxa (species) is a new function qc_taxa().
Issue #13

**Comment by leppott** [comment]
Example console output:

![image](https://user-images.githubusercontent.com/24276278/85426310-4cdc4c00-b548-11ea-8028-3f7a9c41de07.png)

**Comment by leppott** [comment]
Added "NA", "-", "DV", and "SK" as valid values for Habit.

Otherwise returns error.

![image](https://user-images.githubusercontent.com/24276278/85431134-1e15a400-b54f-11ea-84e2-6ef50365f5d0.png)

**Comment by leppott** [comment]
FFG valid values converted to upper case to avoid showing errors in case:

![image](https://user-images.githubusercontent.com/24276278/85431811-0d196280-b550-11ea-93e7-81c67b6b19a6.png)

**Comment by leppott** [comment]
FFG and Habit check all parts of multi-entry records against the valid values.

For example, ""SW, CN, SP" becomes separate entries for SW, CN, and SP and each is checked against the valid values.  This allows for any combination of valid values to be checked.

**Comment by leppott** [comment]
Added check for fish strata as well.

![image](https://user-images.githubusercontent.com/24276278/85432252-afd1e100-b550-11ea-8198-e1bbcda6e45f.png)
